project_directory: "/home/runner/work/"
#project_directory: "/home/matt/work/asic-workshop/shuttle5/openlane/designs/"

caravel:
    root:           /home/runner/work/zero_to_asic_mpw6/zero_to_asic_mpw6
    gl_dir:         verilog/gl
    test_dir:       verilog/dv
    rtl_dir:        verilog/rtl
    includes_dir:   verilog/includes/
    mgmt_root:      /home/runner/caravel_user_project/mgmt_core_wrapper/
    #mgmt_root:      /home/matt/work/asic-workshop/shuttle5/zero_to_asic_mpw5/mgmt_core_wrapper/
    config:         config.tcl

env: # used for simulation
    GCC_PATH:       /home/runner/riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14/bin/
    GCC_PREFIX:     riscv64-unknown-elf
    PDK_PATH:       /home/runner/pdk/sky130A
    PDK_ROOT:       /home/runner/pdk
    OPENLANE:       /home/runner/openlane
    PDK:            sky130A

lvs:
    PDK_PATH:       ../pdk/sky130A 
    PDK_ROOT:       ../pdk/
    OPENLANE:       ../openlane

